import os
import asyncio
import threading
from pathlib import Path
import cloudinary.uploader  
from core.video_processor import VideoProcessor  

def _documents_root():
    """Menentukan folder output di Desktop user"""
    root = Path.home() / "Desktop" / "GNX Production"
    root.mkdir(parents=True, exist_ok=True)
    return root

async def run_gnx_job(payload, job_id, youtube_service, cloudinary_service, **kwargs):
    """
    ALUR KERJA FINAL (INTEGRATED):
    1. YouTube Download -> 2. Face Tracking -> 3. Cloudinary -> 4. YouTube API -> 5. Background Scheduler
    """
    event_handler = kwargs.get("event_handler")

    def log(msg):
        if event_handler: event_handler(type("Event", (), {"message": msg}))
        print(f"[{job_id}] {msg}")

    try:
        log("🚀 Pipeline Started: Full Production Mode...")

        # --- STEP 1: DOWNLOAD ---
        yt_url = payload.get("youtube_url") or payload.get("url")
        temp_dir = _documents_root() / "Temp"
        temp_dir.mkdir(parents=True, exist_ok=True)

        log("📥 Downloading video from YouTube...")
        source_path = youtube_service.download(yt_url, str(temp_dir))
        
        if not source_path or not os.path.exists(source_path):
            raise Exception("Download Gagal: File video tidak ditemukan.")
        log(f"📦 Source ready: {os.path.basename(source_path)}")

        # --- STEP 2: AI HOOKS (OPTIONAL) ---
        try:
            from core.services.ai_content_service import AIContentService
            log("🤖 Processing AI Content...")
            ai_service = AIContentService()
            ai_service.generate_caption(source_path)
            log("✅ AI Content: Success.")
        except Exception as ai_err:
            log(f"⏭️ AI Content: Skipped ({str(ai_err)})")

        # --- STEP 3: VIDEO PROCESSING (FACE TRACKING) ---
        log("🎬 Clipping Video with Face Tracker (Portrait)...")
        out_dir = _documents_root() / "Outputs"
        out_dir.mkdir(parents=True, exist_ok=True)
        output_file = out_dir / f"GNX_{Path(source_path).stem}.mp4"

        class FaceCtx: 
            meta = {
                "face_centering": {
                    "enabled": True, 
                    "mode": "best_face_center",
                    "strategy": "speaker_priority"
                }
            }
        
        processor = VideoProcessor()
        processor.to_portrait(source_path, str(output_file), ctx=FaceCtx())
        log(f"✅ Video Processed: {os.path.basename(output_file)}")

        # --- STEP 4: CLOUDINARY UPLOAD ---
        secure_url = None
        log("☁️ Attempting Cloudinary Upload...")
        try:
            upload_res = cloudinary.uploader.upload(str(output_file), resource_type="video")
            secure_url = upload_res.get("secure_url")
            
            if secure_url:
                log(f"✨ CLOUDINARY SUCCESS: {secure_url}")
            else:
                log("❌ Cloudinary Error: API terhubung tapi URL kosong.")
        except Exception as c_err:
            log(f"❌ CLOUDINARY FAILED: {str(c_err)}")

        # --- STEP 5: DISPATCH TO YOUTUBE & BACKGROUND SCHEDULER ---
        if secure_url:
            log("📲 Initializing Social Media Distribution...")
            targets = payload.get("targets") or ["YouTube"]
            
            # A. Real-Time Upload to YouTube
            if "YouTube" in targets and youtube_service:
                try:
                    log("📡 Uploading to YouTube Channel...")
                    youtube_service.upload_video(
                        file_path=str(output_file),
                        title=f"AutoShorts - {Path(source_path).stem}",
                        description="Generated by GNX AutoShorts Studio",
                        category="22",
                        privacy_status="public"
                    )
                    log("✅ YOUTUBE SUCCESS: Video Published!")
                except Exception as yt_err:
                    log(f"⚠️ YouTube Direct Upload Failed: {str(yt_err)}")

            # B. Background Scheduler (Untuk Antrean Sosmed Lainnya)
            try:
                from core.scheduler_engine import GNXScheduler
                log("⏲️ Sending to Background Scheduler...")
                
                scheduler = GNXScheduler()
                metadata = {
                    "title": f"Shorts {Path(source_path).stem}",
                    "url": secure_url,
                    "targets": targets
                }
                
                # Jalankan di thread terpisah agar UI tidak freeze
                threading.Thread(
                    target=scheduler.process_and_upload, 
                    args=(secure_url, metadata), 
                    daemon=True
                ).start()
                
                log("🚀 SUCCESS: Video masuk antrean Scheduler background!")
            except Exception as sc_err:
                log(f"⚠️ Scheduler Integration Failed: {str(sc_err)}")

            log(f"📝 Tasks initiated for: {', '.join(targets)}")
            log("🏁 PIPELINE COMPLETED SUCCESSFULLY!")
        else:
            log("🛑 Process Terminated: Cloudinary URL tidak tersedia.")

    except Exception as e:
        log(f"🛑 FATAL ERROR: {str(e)}")
        raise e