import os
import asyncio
from pathlib import Path

from core.video_processor import VideoProcessor


class AsyncVideoPipeline:

    def __init__(self, youtube_utils, cloudinary_service, repliz_service):
        self.youtube_utils = youtube_utils
        self.cloudinary_service = cloudinary_service
        self.repliz_service = repliz_service
        self.video_processor = VideoProcessor()

    # =========================================================

    async def process_job(self, job, account_ids=None):

        payload = job.payload

        youtube_url = payload.get("youtube_url")
        offline_path = payload.get("offline_path")
        format_mode = payload.get("format", "portrait")  # portrait | landscape | both

        # ===============================================
        # STEP 1 — GET VIDEO SOURCE
        # ===============================================

        if youtube_url:
            print("Downloading video...")
            source_path = self.youtube_utils.download(
                youtube_url,
                output_dir="temp_downloads"
            )
        elif offline_path:
            if not os.path.exists(offline_path):
                raise Exception("Offline video not found")
            source_path = offline_path
        else:
            raise Exception("No video source provided")

        print("Video source ready:", source_path)

        # ===============================================
        # STEP 2 — FORMAT PROCESSING
        # ===============================================

        output_files = []

        base_name = Path(source_path).stem
        output_dir = "processed_videos"
        os.makedirs(output_dir, exist_ok=True)

        if format_mode == "portrait":
            portrait_path = os.path.join(output_dir, f"{base_name}_9x16.mp4")
            print("Processing portrait format...")
            self.video_processor.to_portrait(source_path, portrait_path)
            output_files.append(portrait_path)

        elif format_mode == "landscape":
            landscape_path = os.path.join(output_dir, f"{base_name}_16x9.mp4")
            print("Processing landscape format...")
            self.video_processor.to_landscape(source_path, landscape_path)
            output_files.append(landscape_path)

        elif format_mode == "both":
            portrait_path = os.path.join(output_dir, f"{base_name}_9x16.mp4")
            landscape_path = os.path.join(output_dir, f"{base_name}_16x9.mp4")

            print("Processing portrait format...")
            self.video_processor.to_portrait(source_path, portrait_path)

            print("Processing landscape format...")
            self.video_processor.to_landscape(source_path, landscape_path)

            output_files.extend([portrait_path, landscape_path])

        else:
            raise Exception("Invalid format mode")

        print("Format processing complete.")

        # ===============================================
        # STEP 3 — UPLOAD & SCHEDULE (MULTI OUTPUT)
        # ===============================================

        for video_file in output_files:

            print("Uploading to Cloudinary...")
            upload_result = self.cloudinary_service.upload(video_file)

            video_url = upload_result.get("secure_url")
            if not video_url:
                raise Exception("Cloudinary upload failed")

            print("Scheduling to Repliz...")
            self.repliz_service.create_schedule(
                title="GNX Generated Video",
                description="Auto generated by GNX AI",
                video_url=video_url,
                account_ids=account_ids or []
            )

        print("Pipeline finished ✔")